### PR TITLE
Fix issue #47

### LINKED ISSUE #47: sunrise and sunset timer fail to schedule at the end of the month (for the first day of the next month)
Hi,
when running the latest version of linknx (compiled yesterday), the sunrise and sunset timer fail to schedule at the end of the month (for the first day of the next month).
This was working in previous versions.

I'll think this is related to the new computation of periodic tasks, somewhere close to line 493 of suncalc.cpp (tryIncreaseClosestGreaterFreeField..), but haven't had time to look closer.

I'll check the next days whether I find the issue and can provide a fix.

But perhaps this is already a known issue?

Regards,
Michael

Example timer coding:

```
 <rule id="Timer_1" init='false'>
	<condition type="timer" trigger="true">
		<at type='sunset' offset='20m'/>
	</condition>
	<actionlist>
		<action type='set-value' id='Mode.Test1' value='1'/>
	</actionlist>
</rule>

```

This is what I get at the end of the month:

```
2020-03-31 20:04:16,734 [ INFO] Rule: Rule: Configuring Timer_1 (active=1)
2020-03-31 20:04:16,734 [ INFO] TimeSpec: 1899-0--1 -1:-1:0 (wdays=0; exception=2)
2020-03-31 20:04:16,734 [ INFO] SolarTimeSpec: sun_rise_set date 2020-3-31
2020-03-31 20:04:16,735 [ INFO] SolarTimeSpec: sun_rise_set returned 19:56
2020-03-31 20:04:16,735 [ INFO] PeriodicTask: No more schedule available
2020-03-31 20:04:16,735 [ INFO] PeriodicTask: Not rescheduled

```

To compare, this is how the log looks like on other days:

```
2020-03-30 20:05:07,861 [ INFO] Rule: Rule: Configuring Timer_1 (active=1)
2020-03-30 20:05:07,861 [ INFO] TimeSpec: 1899-0--1 -1:-1:0 (wdays=0; exception=2)
2020-03-30 20:05:07,861 [ INFO] SolarTimeSpec: sun_rise_set date 2020-3-30
2020-03-30 20:05:07,861 [ INFO] SolarTimeSpec: sun_rise_set returned 19:54
2020-03-30 20:05:07,861 [ INFO] SolarTimeSpec: sun_rise_set date 2020-3-31
2020-03-30 20:05:07,861 [ INFO] SolarTimeSpec: sun_rise_set returned 19:56
2020-03-30 20:05:07,861 [ INFO] PeriodicTask: Rescheduled at 2020-3-31 20:16:00 (1585678560)

```

### PR DESCRIPTION
**Pull request by 2franix**
Fixes #47 by ensuring day provided by SolarTimeSpec is always projected onto actual calendar, as day, month and year are always fully constrained by this type of time spec. The fact that the projection was not happening before caused the logic in PeriodicTask::findNext to fail as the reported scenario was making SolarTimeSpec to select March 32nd. PeriodicTask::findNext then failed to satisfy this impossible constraint.

### CODE REVIEW

File: src/timermanager.cpp [hunk 1]
```diff
@@ -28,254 +28,254 @@ Logger& TimerManager::logger_m(Logger::getInstance("TimerManager"));
...
 DateTime::DateTime(const tm *time)
 {
-	fields_m[0] = time->tm_year;	
-	fields_m[1] = time->tm_mon;	
-	fields_m[2] = time->tm_mday;	
-	fields_m[3] = time->tm_hour;	
-	fields_m[4] = time->tm_min;	
-	freeFields_m = 0x1F;
-	weekdays_m = 0;
+    fields_m[0] = time->tm_year;
```
Comment (2franix) [inline src/timermanager.cpp]: This file only contains indenting changes. Nothing relevant here.

File: test/PeriodicTaskTest.cpp [hunk 2]
```diff
@@ -790,6 +791,34 @@ class PeriodicTaskTest : public CppUnit::TestFixture, public ChangeListener
         CPPUNIT_ASSERT_EQUAL(118, timeinfo->tm_year);
     }
 
+    void testFindNextSunsetWithMonthChange()
```
Comment (2franix) [inline test/PeriodicTaskTest.cpp]: New test added to reproduce the problem.

File: src/suncalc.cpp [hunk 3]
```diff
@@ -475,61 +475,62 @@ double SolarNoonTimeSpec::computeTime(double rise, double set) const
...
+    getTime(currentDate.getDay(), currentDate.getMonth(), currentDate.getYear(), min, hour);
+    DateTime solarTime(currentDate);
+    solarTime.setHour(hour);
+    solarTime.setMinute(min);
+    if (solarTime < currentDate)
+    {
+        // Solar time has already been reached for the current day. Let's move
+        // to the next day that complies with constraints.
+        solarTime.tryIncreaseClosestGreaterFreeField(DateTime::Day);
+        solarTime.tryResolve(currentDate, DateTime::Year, DateTime::Day);
```
Comment (2franix) [inline src/suncalc.cpp]: This line is the actual fix. It makes sure solarTime is modified to correspond to an existing day in the calendar. So for the example reported in #47, solarTime is changed from March 32nd to April 1st. The thing is that SolarTimeSpec returns a value for day and month and PeriodicTask::findNext will then consider those values as frozen. The simplest solution is to make sure that SolarTimeSpec only returns resolved (hence projected on the actual calendar) values. 
I am not sure line 493 is even required now. And this could be executed even when solarTime >= currentDate (that would simply have no effect).
